### ISSUE TITLE
Error while building for land

### ISSUE THREAD

**Issue by rupansh** [pixeldustproject-o/manifest#13]
branch - o2-caf
Tree(s) - github.com/TeamReloaded
error - https://hastebin.com/noqiludowu.xml
Please help!

**Comment by spezi77** [comment]
I think that @mg712702 could have the knowledge about how to fix this.

**Comment by mg712702** [comment]
It's your tree problem

**Comment by rupansh** [comment]
@mg712702 Of course not. I have built omni, Lineage without any problem :C . Is it possible that this rom doesn't support treble yet?

**Comment by mg712702** [comment]
Yup, the Rom doesn't support treble & as of now, we do not have any plan to add support for treble...
NVM, TREBLE=TROUBLE

**Comment by rupansh** [comment]
@mg712702 All right thanks for the help.
